version: "3"
services:
  
  ui:
   build:
      context: ./ui
      dockerfile: Dockerfile.dev
   ports:
    -  3000:3000
   container_name: mern-ui
   networks:
    -  mern-stack-net
   volumes:
    -  ./ui:/usr/app/src
    -  ./ui/public:/usr/app/public
   stdin_open: true
   tty: true

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db
      
  rasa:
    image: rasa/rasa:3.4.1-full
    ports:
      - 5005:5005
    volumes:
      - ./rasa:/app
    command: run --enable-api --cors "*"
    
  action-server:
    container_name: rasa-action-server
    image: rasa/rasa:3.4.1-full
    ports:
      - 5055:5055
    volumes:
      - ./rasa/actions:/app/actions
    command: run actions -p 5055 --cors "*"

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local