# Pull the Node image from Docker Hub
FROM node:14-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

EXPOSE 3000

# Run React Unit Tests.
# May want to run from a test dockerfile/ staged build.
# If tests fail, build will not complete.
ENV CI=true
RUN npm test

# Run the React app
CMD ["npm", "start"]



